export {
  Tab,
  TabList,
  TabPanel,
  Tabs,
  type TabListProps,
  type TabPanelProps,
  type TabProps,
  type TabsActivationMode,
  type TabsBaseProps,
  type TabsOrientation,
  type TabsProps,
  type TabsSize,
  type TabsTone,
} from "./Tabs";
