export type CrewIntelViewModel = {
  id: string;
  name: string;
  tag: string;
  tierLabel: string;
  locationLabel: string;
  emblemSrc: string;
  rank: number;
  trust: number;
  verified: boolean;
  reputationLabel: string;
  membersLabel: string;
  winRateLabel: string;
  warRecordLabel: string;
  ownerName?: string;
  captainNames?: readonly string[];
  activeRosterCount?: number;
  recentResults?: readonly ("W" | "D" | "L")[];
  crewHref: string;
  joinWarHref: string | null;
};
